version: "2"

run:
  timeout: 3m

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused
    - gosec
    - misspell

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gosec
          - errcheck

formatters:
  enable:
    - gofumpt
    - goimports

  settings:
    gofumpt:
      module-path: learn

    goimports:
      local-prefixes:
        - learn
