// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (PracticeSubscription, error)
	DeleteSubscription(ctx context.Context, id int32) error
	GetSubscriptionByID(ctx context.Context, id int32) (PracticeSubscription, error)
	GetSubscriptionsTotal(ctx context.Context, arg GetSubscriptionsTotalParams) (int64, error)
	ListSubscriptions(ctx context.Context, arg ListSubscriptionsParams) ([]PracticeSubscription, error)
	UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) (PracticeSubscription, error)
}

var _ Querier = (*Queries)(nil)
