// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type PracticeSubscription struct {
	ID          int32              `json:"id"`
	ServiceName string             `json:"service_name"`
	Price       int32              `json:"price"`
	StartDate   time.Time          `json:"start_date"`
	EndDate     *time.Time         `json:"end_date"`
	UserID      uuid.UUID          `json:"user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
