// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO practice.subscription (service_name,
                                   price,
                                   start_date,
                                   end_date,
                                   user_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING
    id, service_name, price, start_date, end_date, user_id, created_at, updated_at
`

type CreateSubscriptionParams struct {
	ServiceName string     `json:"service_name"`
	Price       int32      `json:"price"`
	StartDate   time.Time  `json:"start_date"`
	EndDate     *time.Time `json:"end_date"`
	UserID      uuid.UUID  `json:"user_id"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (PracticeSubscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.ServiceName,
		arg.Price,
		arg.StartDate,
		arg.EndDate,
		arg.UserID,
	)
	var i PracticeSubscription
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.Price,
		&i.StartDate,
		&i.EndDate,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSubscription = `-- name: DeleteSubscription :exec
DELETE
FROM practice.subscription
WHERE id = $1
`

func (q *Queries) DeleteSubscription(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteSubscription, id)
	return err
}

const getSubscriptionByID = `-- name: GetSubscriptionByID :one
SELECT id, service_name, price, start_date, end_date, user_id, created_at, updated_at
FROM practice.subscription
WHERE id = $1
`

func (q *Queries) GetSubscriptionByID(ctx context.Context, id int32) (PracticeSubscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByID, id)
	var i PracticeSubscription
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.Price,
		&i.StartDate,
		&i.EndDate,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionsTotal = `-- name: GetSubscriptionsTotal :one
SELECT COALESCE(SUM(s.price), 0)::bigint AS total_price
FROM practice.subscription AS s
         JOIN generate_series(
        $3::date,
        $4::date,
        interval '1 month'
              ) AS months(month_start)
              ON s.start_date <= months.month_start
                  AND (
                     s.end_date IS NULL
                         OR s.end_date >= months.month_start
                     )
WHERE s.service_name = $1
  AND s.user_id = $2
`

type GetSubscriptionsTotalParams struct {
	ServiceName string    `json:"service_name"`
	UserID      uuid.UUID `json:"user_id"`
	PeriodStart time.Time `json:"period_start"`
	PeriodEnd   time.Time `json:"period_end"`
}

func (q *Queries) GetSubscriptionsTotal(ctx context.Context, arg GetSubscriptionsTotalParams) (int64, error) {
	row := q.db.QueryRow(ctx, getSubscriptionsTotal,
		arg.ServiceName,
		arg.UserID,
		arg.PeriodStart,
		arg.PeriodEnd,
	)
	var total_price int64
	err := row.Scan(&total_price)
	return total_price, err
}

const listSubscriptions = `-- name: ListSubscriptions :many
SELECT id, service_name, price, start_date, end_date, user_id, created_at, updated_at
FROM practice.subscription
ORDER BY id DESC
LIMIT $1 OFFSET $2
`

type ListSubscriptionsParams struct {
	Limit  int `json:"limit"`
	Offset int `json:"offset"`
}

func (q *Queries) ListSubscriptions(ctx context.Context, arg ListSubscriptionsParams) ([]PracticeSubscription, error) {
	rows, err := q.db.Query(ctx, listSubscriptions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PracticeSubscription{}
	for rows.Next() {
		var i PracticeSubscription
		if err := rows.Scan(
			&i.ID,
			&i.ServiceName,
			&i.Price,
			&i.StartDate,
			&i.EndDate,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubscription = `-- name: UpdateSubscription :one
UPDATE practice.subscription
SET service_name = $2,
    price        = $3,
    start_date   = $4,
    end_date     = $5,
    user_id      = $6,
    updated_at   = now()
WHERE id = $1
RETURNING
    id, service_name, price, start_date, end_date, user_id, created_at, updated_at
`

type UpdateSubscriptionParams struct {
	ID          int32      `json:"id"`
	ServiceName string     `json:"service_name"`
	Price       int32      `json:"price"`
	StartDate   time.Time  `json:"start_date"`
	EndDate     *time.Time `json:"end_date"`
	UserID      uuid.UUID  `json:"user_id"`
}

func (q *Queries) UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) (PracticeSubscription, error) {
	row := q.db.QueryRow(ctx, updateSubscription,
		arg.ID,
		arg.ServiceName,
		arg.Price,
		arg.StartDate,
		arg.EndDate,
		arg.UserID,
	)
	var i PracticeSubscription
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.Price,
		&i.StartDate,
		&i.EndDate,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
